Class {
	#name : 'SpDragAndDropTransferToList',
	#superclass : 'SpDragAndDropTransfer',
	#instVars : [
		'index'
	],
	#category : 'Spec2-Adapters-Morphic-Support',
	#package : 'Spec2-Adapters-Morphic',
	#tag : 'Support'
}

{ #category : 'accessing' }
SpDragAndDropTransferToList >> index [

	^ index
]

{ #category : 'accessing' }
SpDragAndDropTransferToList >> index: anInteger [

	index := anInteger
]
