Class {
	#name : 'SpDragAndDropTransferToTree',
	#superclass : 'SpDragAndDropTransferToTable',
	#instVars : [
		'target'
	],
	#category : 'Spec2-Adapters-Morphic-Support',
	#package : 'Spec2-Adapters-Morphic',
	#tag : 'Support'
}

{ #category : 'accessing' }
SpDragAndDropTransferToTree >> target [

	^ target
]

{ #category : 'accessing' }
SpDragAndDropTransferToTree >> target: anObject [

	target := anObject
]
