"
I am a demo page for the spec examples demo app to exemplify the use of SpScrollablePresenters
"
Class {
	#name : #SpExecutableLayoutPresenterExample,
	#superclass : #SpDemoPage,
	#category : #'Spec2-Examples-Layouts'
}

{ #category : #initialization }
SpExecutableLayoutPresenterExample class >> pageName [

	^'Scrollable layout'

]

{ #category : #initialization }
SpExecutableLayoutPresenterExample >> pageClass [

	^SpExecutableLayoutExamplePage 

]
