"
I contains deprecated classes/methods of Spec that will be removed in Pharo 9.
"
Class {
	#name : 'ManifestSpec2Deprecated',
	#superclass : 'PackageManifest',
	#category : 'Spec2-Deprecated-Manifest',
	#package : 'Spec2-Deprecated',
	#tag : 'Manifest'
}

{ #category : '*Spec2-Deprecated' }
ManifestSpec2Deprecated class >> isDeprecated [
	^ true
]

{ #category : '*Spec2-Deprecated' }
ManifestSpec2Deprecated class >> isDeprecated [
	^ true
]
