"
Use my superclass. I am deprecated.
"
Class {
	#name : 'SpCurrentSpecDefaultBindings',
	#superclass : 'SpBindings',
	#category : 'Spec2-Deprecated-Obsolete',
	#package : 'Spec2-Deprecated',
	#tag : 'Obsolete'
}

{ #category : '*Spec2-Deprecated' }
SpCurrentSpecDefaultBindings class >> isDeprecated [
	^ true
]

{ #category : '*Spec2-Deprecated' }
SpCurrentSpecDefaultBindings class >> isDeprecated [
	^ true
]
