Extension { #name : #SpLabelledDropListButtonTest }

{ #category : #'*Spec2-Deprecated' }
SpLabelledDropListButtonTest >> classToTest [
	^ SpLabelledDropListButton
]

{ #category : #'*Spec2-Deprecated' }
SpLabelledDropListButtonTest class >> isDeprecated [
	"This presenter does not add enough value to Spec to be kept in it. If you are using it, please copy the code in your own application."

	^ true
]
