"
I am the adapter used to bridge an IconListPresenter and a PluggableIconListMorph
"
Class {
	#name : 'SpMorphicIconListAdapter',
	#superclass : 'SpMorphicListAdapter',
	#category : 'Spec2-Deprecated-Adapters',
	#package : 'Spec2-Deprecated',
	#tag : 'Adapters'
}

{ #category : '*Spec2-Deprecated' }
SpMorphicIconListAdapter class >> isDeprecated [
	^ true
]

{ #category : '*Spec2-Deprecated' }
SpMorphicIconListAdapter class >> isDeprecated [
	^ true
]
