"
A TestingAbstractTwoButtons is a stupid AbstractTwoButtons used to test it.
"
Class {
	#name : 'SpTestingAbstractTwoButtons',
	#superclass : 'SpAbstractTwoButtons',
	#category : 'Spec2-Deprecated-Obsolete',
	#package : 'Spec2-Deprecated',
	#tag : 'Obsolete'
}

{ #category : '*Spec2-Deprecated' }
SpTestingAbstractTwoButtons class >> example [
	<sampleInstance>
	^ self abstractExample openWithSpec 
]

{ #category : '*Spec2-Deprecated' }
SpTestingAbstractTwoButtons class >> example [
	<sampleInstance>
	^ self abstractExample openWithSpec 
]

{ #category : '*Spec2-Deprecated' }
SpTestingAbstractTwoButtons >> initializeButtons [
]

{ #category : '*Spec2-Deprecated' }
SpTestingAbstractTwoButtons >> initializeButtons [
]
