"
A TestingAbstractTwoButtons is a stupid AbstractTwoButtons used to test it.
"
Class {
	#name : #SpTestingAbstractTwoButtons,
	#superclass : #SpAbstractTwoButtons,
	#category : #'Spec2-Deprecated-Obsolete'
}

{ #category : #'*Spec2-Deprecated' }
SpTestingAbstractTwoButtons class >> example [
	<sampleInstance>
	^ self abstractExample openWithSpec 
]

{ #category : #'*Spec2-Deprecated' }
SpTestingAbstractTwoButtons >> initializeButtons [
]
