Class {
	#name : #ColumnedListPresenterTest,
	#superclass : #ListPresenterTest,
	#category : #'Spec-Tests-Core-Widgets'
}

{ #category : #running }
ColumnedListPresenterTest >> classToTest [
	
	^ TablePresenter
]

{ #category : #tests }
ColumnedListPresenterTest >> testSelectAll [
	"Not implemented yet"
	^ self skip.
]

{ #category : #tests }
ColumnedListPresenterTest >> testWhenListChangedOldContents [
	"Not implemented yet"
	^ self skip.
]
