Extension { #name : 'SpApplicationBackend' }

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> dropListClass [

	self subclassResponsibility
]

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> listClass [

	self subclassResponsibility
	
]

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> switchClass [

	self subclassResponsibility
]

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> tableClass [

	self subclassResponsibility
]

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> treeClass [

	self subclassResponsibility
	
]

{ #category : '*Spec2-ListView' }
SpApplicationBackend >> treeTableClass [

	self subclassResponsibility
]
