Extension { #name : 'SpMorphicBackend' }

{ #category : '*Spec2-ListView' }
SpMorphicBackend >> dropListClass [

	^ SpDropListPresenter
]

{ #category : '*Spec2-ListView' }
SpMorphicBackend >> listClass [

	^ SpListPresenter
]

{ #category : '*Spec2-ListView' }
SpMorphicBackend >> tableClass [

	^ SpTablePresenter
]

{ #category : '*Spec2-ListView' }
SpMorphicBackend >> treeClass [

	^ SpTreePresenter	
]

{ #category : '*Spec2-ListView' }
SpMorphicBackend >> treeTableClass [

	^ SpTreeTablePresenter
]
