"
A TestingAbstractTwoButtons is a stupid AbstractTwoButtons used to test it.
"
Class {
	#name : #SpTestingAbstractTwoButtons,
	#superclass : #SpAbstractTwoButtons,
	#category : #'Spec-Deprecated80'
}

{ #category : #'as yet unclassified' }
SpTestingAbstractTwoButtons class >> example [
	<sampleInstance>
	^ self abstractExample openWithSpec 
]

{ #category : #initialization }
SpTestingAbstractTwoButtons >> initializeButtons [
]
