Class {
	#name : #SpUseForTestWithMethodBySpMethodChooserUI,
	#superclass : #Object,
	#instVars : [
		'biChooseMethod'
	],
	#category : #'Spec2-PolyWidgets-Tests-mock'
}

{ #category : #'as yet unclassified' }
SpUseForTestWithMethodBySpMethodChooserUI class >> gandalf [
]

{ #category : #useForTest }
SpUseForTestWithMethodBySpMethodChooserUI >> ahhhhhhhhhhhhhhh [

]

{ #category : #useForTest }
SpUseForTestWithMethodBySpMethodChooserUI >> banane [
]

{ #category : #useForTest }
SpUseForTestWithMethodBySpMethodChooserUI >> leonNettoyeur [
]

{ #category : #useForTest }
SpUseForTestWithMethodBySpMethodChooserUI >> pommeDeTerre [
]
